name: Ubuntu/x86_64

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo,
  # etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and
    # should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform
    # coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install scons
      run: sudo apt-get install scons

    - name: Install tiny-xml
      run: sudo apt-get install libtinyxml-dev

    - name: Install lua5.1
      run: sudo apt-get install liblua5.1-0-dev

    - name: Install boost
      run: |
        sudo apt-get install libboost-dev
        sudo apt-get install libboost-system-dev
        sudo apt-get install libboost-filesystem-dev

    - name: Build
      working-directory: ${{github.workspace}}
      run: |
        echo ${{github.workspace}}
        scons conf=release target=linux-ubuntu -j$(nproc)

    - name: Test
      working-directory: ${{github.workspace}}/test
      run: |
        python xsdparse-test.py
        python python-sax-test.py
        python java-json.org-test.py
        python c-xml-expat-test.py
        python c-xml-expat-dom-test.py
